name: Docker Image CI

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened, edited ]
    branches: [ "main" ]

permissions:
  contents: write

jobs:

  build:
    if: contains(github.event.pull_request.labels.*.name, 'tag:')
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Get Tag name
      id: get-tag
      shell: bash
      run: |
        set -x
        CHARS="\","
        TAG=$(echo $LABELS | jq | grep tag: | sed "s/[$CHARS]//g" | tr -d ' ')
        echo "tag=${TAG#tag:}" >> "$GITHUB_OUTPUT"
      env: 
        LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}
    
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: hello/
        push: true
        tags: zhoudoris13/hello-elixir:${{ steps.get-tag.outputs.tag }}

    - name: Update Tag in values file
      if: github.event.action == 'labeled' && startsWith(github.event.label.name, 'tag:')
      run: |
        git config --global user.name 'Dahlia Zhou'
        git config --global user.email 'dahlizhou13@users.noreply.github.com'
        git checkout $GITHUB_HEAD_REF
        yq -i '.image.tag = strenv(TAG)' hello/values.yaml
        git commit -am "Automated report"
        git push
      shell: bash
      env:
        TAG: ${{ steps.get-tag.outputs.tag }}