name: Docker Image CI

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened, edited ]
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get Tag name
      id: get-tag
      shell: bash
      run: |
        set -x
        CHARS="[],"
        TAG=$(echo $LABELS | grep tag: | sed "s/[$CHARS]//g")
        echo "tag=${TAG#tag:}" >> "$GITHUB_OUTPUT"
      env: 
        LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: hello/
        push: true
        tags: zhoudoris13/hello-elixir:${{ steps.get-tag.outputs.tag }}
